version: '3'

services:
  nodejs-app:
    build: .
    container_name: nodejs-app
    ports:
      - "4000:3000"
    networks:
      - localprom

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.2
    container_name: cadvisor
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - "prometheus"
      - "grafana"
      - "nodejs-app"
      - "node_exporter"
    networks:
      - localprom

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
    restart: unless-stopped
    networks:
      - localprom

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - '3000:3000'
    volumes:
      - grafana-data:/var/lib/grafana
      - ./datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yml
    restart: unless-stopped
    depends_on:
      - prometheus
    networks:
      - localprom

  node_exporter:
    image: quay.io/prometheus/node-exporter:v1.5.0
    container_name: node_exporter
    ports:
      - '9100:9100'
    command: --path.rootfs=/
    pid: host
    restart: unless-stopped
    networks:
      - localprom

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - '3100:3100'
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - /tmp/loki:/tmp/loki
      - ./local-config.yaml:/etc/loki/local-config.yaml
    restart: unless-stopped
    user: root
    networks:
      - localprom

  promtail:
    container_name: promtail
    image: grafana/promtail:2.3.0
    restart: unless-stopped
    volumes:
      - /var/lib/docker/containers/**:/var/lib/docker/containers:ro
      - ./promtail-config.yaml:/etc/promtail/promtail-config.yaml
    command: -config.file=/etc/promtail/promtail-config.yaml
    networks:
      - localprom
    depends_on:
      - loki

  # jaeger:
  #   image: jaegertracing/all-in-one:latest
  #   container_name: jaeger
  #   ports:
  #     - "16686:16686"
  #   networks:
  #     - localprom

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - localprom


networks:
  localprom:
    driver: bridge

volumes:
  grafana-data:
    driver: local
