global:
  scrape_interval: "15s"
  evaluation_interval: "15s"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
    metrics_path: '/metrics'
    scheme: 'http'

  - job_name: "cadvisor"
    static_configs:
      - targets: ['cadvisor:8080']
    #metrics_path: '/metrics'
    scheme: 'http'

  - job_name: 'nodejs-app'
    static_configs:
      - targets: ['nodejs-app:4000']
    metrics_path: '/metrics'
    scheme: 'http'

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']
    scheme: 'http'
